### ISSUE TITLE
Error trying to query Picasa API. Response status: 404

### ISSUE THREAD

**Issue by GreyGrump** [inetis-ch/oc-GooglePhotos-plugin#10]
Hi Guys, I'm getting the titled error when I click "Preview" on my Album page.
I can load the Gallery page and the Album page just fine but when I click an image in an album I have an empty modal pop up. Images below should help explain......

This is the exception error when I try to Preview the Album page...
![exception](https://user-images.githubusercontent.com/37731734/37861903-fd41b46a-2f97-11e8-8785-141bed6a2667.jpg)

This is my album page settings...
![album](https://user-images.githubusercontent.com/37731734/37861911-279ea9b6-2f98-11e8-8eb2-00a27550a492.jpg)

This is my gallery page settings...
![gallery](https://user-images.githubusercontent.com/37731734/37861915-47fd72a0-2f98-11e8-9b3e-b704e678fddf.jpg)

This is the empty modal I get when clicking an image in an album...
![popup_window](https://user-images.githubusercontent.com/37731734/37861923-8a01796c-2f98-11e8-8687-12e37a9dd578.jpg)

I'm assuming the modal comes up empty due to the Http referrer error, but not sure why this would happen only for the actual image and not the Gallery/Album access.
Have checked & quadruple checked my settings and followed instructions but coming up short for a solution.
Cheers, 8-)

**Comment by GreyGrump** [comment]
Mmmm  nearly a week and no response... I guess this plugin is now un-supported.
Plugin un-installed.
 8-/

**Comment by Fl0Cri** [comment]
Hello, sorry for my late reply, I didn't see your issue.
Do you still want to try debugging it?

**Comment by GreyGrump** [comment]
Hi, no worries... better late than never ;-)

I have removed it from my system but would be happy to re-install and debug. Much prefer to use google's bandwidth than my own. 
8-)

**Comment by Fl0Cri** [comment]
Ok, I didn't uderstand exactly where do you get the error page at the beginning?
Because later you can get to the album page (where images of the album are displayed), right?

The problem seems to be the full size images (when you click on a thumbnail, it should open a modal with the original image inside).
But before opening the modal are you seeing the thumbnails or are they blank like the full one?

**Comment by GreyGrump** [comment]
The error comes up when I click "**Preview**" on my Album page in October/Backend/CMS/Pages.

Yes, I can see the Gallery (All Albums) and can see the Album (All thumbs) but when clicking a thumb for full image the modal comes up empty (as per last image).

**Comment by Fl0Cri** [comment]
Ok, the preview from the backend is a "normal" error: October can't know what to fill for the `:albumId` parameter, so the plugin ends up trying to query GooglePhotos for a wrong album id.

For the full image not showing, I see two possibilities:
- A JS / browser issue: There is a piece of JavaScript to display the image inside the modal, maybe your browser doesn't like it. Try to click on an image on the following page (working for me) and tell me if it works. https://demo.inetis.ch/plugins/google-photos/album/6437053746716000689
- It may be an issue with the full image ulrs not being accepted by Google, but it would be surprising because it's exactly what is returned by the API.

Can you try the first point, if it works on our demo site, try the following.
On your site, right-click on a thumb -> inspect element, then copy the url inside the `href` attribute of the closest `<a>` tag and try to open it in a new browser tab. Tell me if it works or if you get an error message.
![outils de developpement - october cms - google photos album - https___demo inetis ch_plugins_google-photos_album_6437053746716000689 2018-04-03 12 52 11](https://user-images.githubusercontent.com/16371551/38245555-c703c66e-373e-11e8-9760-9e371bdad250.png)

**Comment by GreyGrump** [comment]
OK, the demo @ https://demo.inetis.ch/plugins/google-photos/album/6437053746716000689 
works fine for me in Chrome, Firefox and Comodo Dragon browsers.

When I Inspect Element, copy image link and open in new browser tab, it **"downloads"** the **full** image but won't display it in the browser. Very strange.... 8-/
![image1](https://user-images.githubusercontent.com/37731734/38247534-07916624-3789-11e8-865a-c7f20717603b.jpg)


Oh, probably should add.....
I'm running a heavily customised version of Veg Pro theme, and include all the normal JS and Bootstrap3 components.

**Comment by Fl0Cri** [comment]
Ok, now can you try to right-click -> inspect on the modal?
You should have something like this:
![outils de developpement - october cms - google photos album - https___demo inetis ch_plugins_google-photos_album_6437053746716000689 2018-04-03 14 00 10](https://user-images.githubusercontent.com/16371551/38248027-615b23a8-3747-11e8-99f4-b99098371335.png)

If you doesn't have the `<img>`, then we'll be sure it's a script issue.
Can you check if you have errors in the JS console?
Check also that you have both Bootstrap and jQuery loaded (and what version of Bootstrap are you using?).

**Comment by GreyGrump** [comment]
Modal inspection comes up empty... no `<img>`.
Running Bootstrap v3.3.5 ... jQuery v1.12.4

I do have some JS errors......

![image3](https://user-images.githubusercontent.com/37731734/38250212-83984ece-3791-11e8-8147-530abd4ea3b1.jpg)

![image4](https://user-images.githubusercontent.com/37731734/38250240-99caef76-3791-11e8-89c7-c429556d614a.jpg)

Also a couple of facebook.embed.js errors which I'll clean up tomorrow.
After midnight here now so I'm hitting the hay.
Thanks for your help, will pick this up again tomorrow.

Cheers, 8-)

**Comment by Fl0Cri** [comment]
Ok, have a good night ;-)
Your jQuery seems to be in "noConflict" mode. Unless you have an other library that uses the global `$` variable, you can disable the noConflict and it should fix the problem

**Comment by GreyGrump** [comment]
Ahh yes... I simply removed `jQuery.noConflict();` from the last line of my jquery.js file and this has solved the issue.

Thank you very much. 8-)
