### ISSUE TITLE
Plugin no longer works 

### ISSUE THREAD

**Issue by bjlatta** [inetis-ch/oc-GooglePhotos-plugin#11]
the api is return a response of 400! Even your demo no longer works. This only happened a short while ago. I suspect that google has made a change in there api. This happens on both my development and production site. By the way your demo causes and error as well. Any help would be appreciated. I have be using this plugin for some time now and it is wonderful and looking forward to a solution.

![exception](https://user-images.githubusercontent.com/8021256/51394265-d20b3800-1aee-11e9-91fe-eaa50c1df1c5.jpg)

**Comment by Fl0Cri** [comment]
Noticed this morning too that Google is turning off his PicasaWebData api. We were using it because there was no "Google Photos" equivalent at the time this plugin was written.

We are working to port the plugin to the Google Photos API, a new release should be ready next week.

Fortunately there is a flag that we can use to report the deprecation to March 15th. Release 1.2.3 of the plugin is using it so you can update to fix the issue.

**Comment by bjlatta** [comment]
Thanks so much for the very quick response! You are awesome. Love the plugin!!!
